services:
  examboard:
    build: .
    command: node ace serve --hmr
    volumes:
      - .:/tera
      - tera_node_modules:/tera/node_modules
    restart: unless-stopped
    env_file: .env
    ports:
      - "3333:3333"
    depends_on:
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - examboard

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - examboard
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - examboard

networks:
  examboard:
    driver: bridge

volumes:
  mysql_data:
  tera_node_modules:
